### ISSUE TITLE
Dot Conversion to Number Error

### ISSUE THREAD

**Issue by DarioS** [genepi/haplogrep3#35]
I have a VCF file which is a merge of a set of VCF files and hence some columns have all values set to `.`.

```
##source=DRAGEN_SNV
##bcftools_mergeVersion=1.16+htslib-1.16
##bcftools_mergeCommand=merge -Oz -o allGermline.vcf.gz 010_Fibro.hard-filtered.vcf.gz 090_Fibro.hard-filtered.vcf.gz ...
##bcftools_viewVersion=1.16+htslib-1.16
    ...        ...
chrM    72      .       T       C       .       PASS    MQ=208.6;FractionInformativeReads=1 ...
chrM    73      .       A       G       .       PASS    MQ=192.56;FractionInformativeReads=0.999 ...    
    ...        ...
```

Haplogrep 3 doesn't like it.

```
Haplogrep 3 3.2.1
java.lang.NumberFormatException: For input string: "."
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:651)
        at java.base/java.lang.Double.valueOf(Double.java:614)
       ...        ...
        at genepi.haplogrep3.App.main(App.java:131)
```
Could it be more gracefully caught and ignored?

**Comment by seppinho** [comment]
Will provide a fix!

**Comment by DarioS** [comment]
Has to be txt file suffix for GitHub to allow it: [test.vcf.txt](https://github.com/genepi/haplogrep3/files/14614822/test.vcf.txt)

**Comment by seppinho** [comment]
thx!

**Comment by DarioS** [comment]
Will you fix this bug soon or not?

**Comment by ramprasadn** [comment]
Hey @seppinho, I'm running into the same issue. Is there a fix for this?
